name: Build and deploy a container to an Amazon Container Registry

env:
  APP_NAME: speed-test
  AWS_REGION: ap-south-1

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract ECR repository URI
        id: ecr
        run: |
          echo "::set-output name=uri::$(aws ecr describe-repositories --repository-names ${{ env.APP_NAME }} --region ${{ secrets.AWS_REGION }} --query "repositories[0].repositoryUri" --output text)"

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ steps.ecr.outputs.uri }}:${{ github.sha }} --push .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SSH and Deploy Docker Container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ec2-user # Replace with your EC2 instance's SSH username
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region ${{ env.AWS_REGION }}
            sudo docker login -u AWS -p $(aws ecr get-login-password --region ${{ env.AWS_REGION }}) ${{ steps.ecr.outputs.uri }}
            sudo docker pull ${{ steps.ecr.outputs.uri }}:${{ github.sha }}
            sudo docker run -d -p 80:80 ${{ steps.ecr.outputs.uri }}:${{ github.sha }}
